### ISSUE TITLE
Quiver timeline, diachronic view - enlarge diagram on demand (for a more detailed view)

### ISSUE THREAD

**Issue by MareenGeestmann** [OCR-D/quiver-frontend#44]
Enable to enlarge diagram on demand (for a more detailed view).

New details: 
- x- and y-axis lables
    - on x-axis: release date.
    - on y-axis: metric and unit (if applicable); e. g. "wall time in minutes" or "Pages per minute".
    - Align the label centered on the axis.
- x-axis values
- title
    - document, workflow (or "average")

Note: Labels must be shown when plot is enlarged, but can be ommitted when in preview (for a cleaner look as many charts are shown).

Please enlarge font size of axis values.

**Comment by paulpestov** [comment]
> Please add x-axis label ("release date"). It is not self-explaning what date it is.

The x-axis is just time, it is not a release date. Release date are now marked as dashed lines within the chart.

> Please add document name to title.

The document name apprears to be often quite long and is also visible in the timeline item. I think the connection to the document should be clear when the user opens several detail charts within one timeline item. So I thought the workflow name should be enough.

> Was the font size of the axis values increased? (if yes, even larger would be more legible)

Yes, it is 11px. Larger font size will have negative effect on readability for the dates on the x-axis.


For the rest, fixes incoming.

**Comment by MareenGeestmann** [comment]
![Image](https://github.com/OCR-D/quiver-frontend/assets/26925926/053213ee-98be-4c1a-af83-716f00def865)


To which document does the plot belong? (through the eye of a naive user)
When the title is too long, then we should use a visual cue.


Please remind me, what kind of date is it then?
The release data markers are nice.

**Comment by MareenGeestmann** [comment]
To sum up, open tasks: 

- add x-axis title "date"
- add units to metric
- add document name to title (or add a visual cue where the plot originates from; dependent what is easiere/ more elegant to implement)

**Comment by MareenGeestmann** [comment]
For documentation purposes, as discussed:
- the unit for wall time and CPU time is "seconds"
- error rates do not have units as they are percentages, values are from 0  to 1 (although higher values are possible as Dinglehopper does not normalize them)

**Comment by noornoorie** [comment]
@MareenGeestmann Should I hardcode the units into the code or would those be provided by backend api?

**Comment by MareenGeestmann** [comment]
I cannot say if they were provided by the API. @paulpestov Do you know it?
If not provided it seems necessary to hardcode it.

**Comment by paulpestov** [comment]
Yes, for now we can hardcode them.
