### ISSUE TITLE
Quiver timeline - add sorting

### ISSUE THREAD

**Issue by MareenGeestmann** [OCR-D/quiver-frontend#46]
Add sorting

- [ ] by each metric (up/down)
- [ ] by gt label (a-z)
- [ ] by year (newest/oldest)

**Comment by jfrer** [comment]
Regarding filtering by year: each gt has a `notBefore` and a `notAfter` year. Currently the order will be the same weather we sort by `notBefore` or `notAfter` but this could theoretically change in the future. Should one of these attributes get priority?
Some (theoretical) example gts:

- 1800-1900 vs. 1832-1864
- 1800-1950 vs. 1801-1850
- 1800-1900 vs. 1800-1850

-> which one should be considered "older"? 
I would say the one with the oldest `notBefore` and if they are the same then the oldest `notAfter`.
By this definition the examples would be:

- 1st older
- 1st older
-  2nd older

But some people might consider the 2nd one of the second example to be older.
What do you think @MareenGeestmann ?

**Comment by MareenGeestmann** [comment]
Thank you for the explanation!
I agree with you. -> the one with the oldest `notBefore` and if they are the same then the oldest `notAfter`.

**Comment by jfrer** [comment]
Should only the average of the latest runs be used for filtering by metric or the average of all runs? I assume only the latest runs but want to be absolutely sure.

**Comment by MareenGeestmann** [comment]
Yes, only the latest run. And consider only the average (this might noch be optimal, but for this view fine enough; there is still the table view for more specific sorting [coming soon]).

**Comment by jfrer** [comment]
This is almost ready for pull request, i just need to wait for #81 to be merged so i can use these changes.
