### ISSUE TITLE
Quiver Tab "Projects" selected although Tab "Workflow" is opened

### ISSUE THREAD

**Issue by MareenGeestmann** [OCR-D/quiver-frontend#57]
When opening the URL https://ocr-d.de/quiver-frontend/#/workflows, the tab "projects" is highlighted although the page "workflow" is opened.
This case also applies when opening https://ocr-d.de/quiver-frontend/#/processors.

Task: Highlight the associated tab.

![Image](https://github.com/OCR-D/quiver-frontend/assets/26925926/f1b3c99d-cfa9-4b6f-bfb3-b9440a19f724)

**Comment by noornoorie** [comment]
@paulpestov
