### ISSUE TITLE
Quiver - select document: omit search line

### ISSUE THREAD

**Issue by MareenGeestmann** [OCR-D/quiver-frontend#64]
Example:
Write "Blumen" in search field.
"Johann Friedrich Blumenbach ... " will be suggested but not filtered. I see no way to confirm.
Expect for deselecting and reselecting the item.

It should be filtered automatically when a selection is made.

see comments below => task: omit search line

**Comment by paulpestov** [comment]
The search feature as of now is a filter of the list in the dropdown. It is not meant to be a selection. The selection is only made via the checkboxes. We can think about omitting the search completely.
