### ISSUE TITLE
Quiver - Favicon

### ISSUE THREAD

**Issue by MareenGeestmann** [OCR-D/quiver-frontend#83]
Add favicon.
(If file is not suitable please let Mareen know or try by yourself. e. g. via https://ocr-d.de/)

![Image](https://github.com/OCR-D/quiver-frontend/assets/26925926/20f02757-6056-4976-bc71-357d1255e51e)

**Comment by jfrer** [comment]
I used the favicon that https://ocr-d.de/ also uses for this. Its a bit smaller, quadratic and includes "CR" in the middle of the "O"/"D".
